default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nutri_tracker_api
  username: sebastianhm
  password: sehemu

test:
  <<: *default
  database: nutri_tracker_api_test
  username: sebastianhm
  password: sehemu

production:
  <<: *default
  database: nutri_tracker_api_production
  username: nutri_tracker_api
  password: <%= ENV["NUTRI_TRACKER_API_DATABASE_PASSWORD"] %>
